### ISSUE TITLE
exact_size does not work.

### ISSUE THREAD

**Issue by NareshBisht** [Joeclinton1/google-images-download#11]
I entered the following command but the images with different sizes were downloaded.

>python google_images_download.py --keywords "baloons" --exact_size 1920,1080 --limit 5

**Comment by NicolasGrosjean** [comment]
Hi  @NareshBisht ,

Thank you for reporting the issue.

I fixed it with the pull request which is quoted above.

**Comment by NareshBisht** [comment]
Thank you @NicolasGrosjean. You are awesome.
