### ISSUE TITLE
Could not open URL

### ISSUE THREAD

**Issue by DP1701** [Joeclinton1/google-images-download#13]
Hi all, I have installed the package with:

```
python setup.py build
python setup.py install
```

Unfortunately I get the message:

```
googleimagesdownload --keywords "Polar bears, baloons, Beaches" --limit 20


Item no.: 1 --> Item name = Polar bears
Evaluating...
Could not open URL. Please check your internet connection and/or ssl settings 
If you are using proxy, make sure your proxy settings is configured correctly
```

Did anyone also get this message? Is there a solution for this?

I do not use a proxy and an Internet connection is available

I just created a python environment and installed the google-images-download package with certifi. 

System is macOS Catalina
Python 3.9

**Comment by tejasa97** [comment]
seems like an internet connectivity issue
