### ISSUE TITLE
Can not download more than 98 images with chromedriver

### ISSUE THREAD

**Issue by DP1701** [Joeclinton1/google-images-download#25]
Hi all, unfortunately I can't download more than 98 images with chromedriver. I get this error message:

```
Unfortunately all 350 could not be downloaded because some images were not downloadable. 98 is all we got for this search filter!

Errors: 2


Everything downloaded!
```

I have entered the following command:
```
googleimagesdownload --keywords "nature" --limit 350 --chromedriver "google-images-download/chromedriver"
```

I also tried with selenium 4.4.3. But unfortunately the same error appears. However, I had to make some adjustments with the newer selenium, because find_element_by_xpath, find_element_by_tag_name and find_element_by_css_selector are deprecated according to the doc.

Does anyone have an idea how I can download more than 97 images?

**Comment by NicolasGrosjean** [comment]
Hi,

Like @Joeclinton1 put in the code [here](https://github.com/Joeclinton1/google-images-download/commit/dcb4619af4246973896bf633fd7c809b6d74f208#diff-25f0141e3d7d9cedd07d9f8f0aa332ab72ee0c7075bbe34210030832dbd1638bR330), I think the [ajax code](https://github.com/Joeclinton1/google-images-download/commit/90e52a4a35c3861fddcc751439064909b166da7d) done by @voins need to be updated.

For the moment, set the limit higher than 100 don't bring more images and make lose time.
So a way to get more images is to play with other parameters to do more queries and get more images.
For example you can use _time_range_, add more keywords with synonyms, ...

**Comment by ogimgio** [comment]
any news on this?
